config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'callbacks'
  }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy'
  end
  root to: 'pages#index'
  resources :projects do
    collection do
      get 'ruby'
      get 'sinatra'
      get 'javascript'
      get 'rails'
      get 'react'
      get 'personal'
    end
    resources :comments
  end
end

app/helpers/navigation_helper.rb
# Helper modules for Navbar
module NavigationHelper
  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end

  def nav_header_content_partials
    partials = []
    partials << 'layouts/navigation/header/toggle_button'
    partials << 'layouts/navigation/header/home_button'
    partials
  end
end

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li><%= link_to 'All Projects', projects_path %></li>
<li><%= link_to 'Login', login_path %></li>
<li><%= link_to 'Signup', signup_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="dropdown pc-menu">
  <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
    <span id="user-name"><%= current_user.name %></span>
    <span class="caret"></span>
  </a>

  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'All Projects', projects_path %></li>
    <li><%= link_to 'New Project', new_project_path %></li>
    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
    <li><%= link_to 'Log out', logout_path, method: :delete %></li>
  </ul>
</li>

  <ul class="mobile-menu" role='menu'>
<li>
  <%= link_to 'All Projects', projects_path %>
</li>
<li class="mobile-menu">
  <%= link_to 'New Project', new_project_path %>
</li>
<li class="mobile-menu">
  <%= link_to 'Edit Profile', edit_user_registration_path %>
</li>
<li class="mobile-menu">
  <%= link_to 'Log out', logout_path, method: :delete %>
</li>
</ul>