config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'callbacks'
  }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy'
  end
  root to: 'pages#index'
  resources :projects do
    collection do
      get 'ruby'
      get 'sinatra'
      get 'javascript'
      get 'rails'
      get 'react'
      get 'personal'
    end
    resources :comments
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 255 }
  validates :description, presence: true, length: { minimum: 20, maximum: 1000 }
  validates :flatiron_module_id, presence: true
  belongs_to :user
  belongs_to :flatiron_module
  has_many :comments
  has_many :flatiron_modules

  #default_scope -> { includes(:user).order(created_at: :desc) }

  scope :by_flatiron_module, ->(branch, flatiron_module_name) do
    joins(:flatiron_module).where(flatiron_modules: { name: flatiron_module_name, branch: branch })
  end

  scope :by_branch, ->(branch) do
    joins(:flatiron_module).where(flatiron_modules: { branch: branch })
  end

  scope :search, ->(search) do
    where('title LIKE lower(?) OR description LIKE lower(?)', "%#{search}%", "%#{search}%")
  end

  scope :alphabetize, -> do
    order(:title)
  end
end

app/controllers/projects_controller.rb
# Controller for all Project views
class ProjectsController < ApplicationController
  before_action :redirect_if_not_signed_in, only: [:new]
  before_action only: [:rails, :ruby, :react, :sinatra, :personal, :javascript] do
    projects_for_branch(params[:action])
  end

  def show
    @comment = Comment.new
    @project = Project.find(params[:id])
    @flatiron_module = @project.flatiron_module
    @comment.project_id = @project.id
  end

  def index
    @projects = Project.alphabetize
    render 'projects'
  end

  def new
    @branch = params[:branch]
    if @branch
      @flatiron_modules = FlatironModule.where(branch: @branch)
    else
      @flatiron_modules = FlatironModule.all.uniq
    end
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_path(@project)
    else
      redirect_to root_path
    end
  end

  def rails
  end

  def sinatra
  end

  def ruby
  end

  def javascript
  end

  def react
  end

  def personal
  end

  private

  def conversation_exist?
    false
  end

  def project_params
    params.require(:project)
          .permit(:description, :title, :flatiron_module_id, :github, :youtube)
          .merge(user_id: current_user.id)
  end

  def projects_for_branch(branch)
    @flatiron_modules = FlatironModule.where(branch: branch)
    @projects = retrieve_projects.paginate(page: params[:page])
    respond_to do |format|
      format.html
      format.js { render partial: 'projects/projects_pagination_page' }
    end
  end

  def retrieve_projects
    ProjectsForBranchService.new(
      { search: params[:search],
        flatiron_module: params[:flatiron_module],
        branch: params[:action] }
    ).call
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def create_new_project_partial_path
    if user_signed_in?
      'projects/branch/create_new_project/signed_in'
    else
      'projects/branch/create_new_project/not_signed_in'
    end
  end

  def all_flatiron_modules_button_partial_path
    if params[:flatiron_module].blank?
      'projects/branch/flatiron_modules/all_selected'
    else
      'projects/branch/flatiron_modules/all_not_selected'
    end
  end

  def no_projects_partial_path(projects)
    projects.empty? ? 'projects/shared/no_projects' : 'shared/empty_partial'
  end

  def project_format_partial_path
    current_page?(root_path) ? 'projects/project/home_page' : 'projects/project/branch_page'
  end

  def flatiron_module_field_partial_path
    if params[:flatiron_module].present?
      'projects/branch/search_form/flatiron_module_field'
    else
      'shared/empty_partial'
    end
  end

  def update_pagination_partial_path
    if @projects.next_page
      'projects/projects_pagination_page/update_pagination'
    else
      'projects/projects_pagination_page/remove_pagination'
    end
  end

  def contact_user_partial_path
    if user_signed_in?
      @project.user.id != current_user.id ? 'projects/show/contact_user' : 'shared/empty_partial'
    else 
      'projects/show/login_required'
    end
  end

  def leave_message_partial_path
    if @message_has_been_sent
      'projects/show/contact_user/already_in_touch'
    else
      'projects/show/contact_user/message_form'
    end
  end
end

app/views/projects/_branch.html.erb
<div id="branch-main-content" class="container">
  <div class="row">
    <h1 class="page-title"><%= page_title %></h1>
    <%= render 'projects/branch/create_new_project', branch: branch %>
  </div>

  <div class="row">
    <%= render  'projects/branch/search_form', 
                branch: branch,
                search_placeholder: search_placeholder %>
  </div>

  <div class="row">
    <%= render 'projects/branch/flatiron_modules', branch: branch %>
  </div>

  <div class="row">
    <div class="col-sm-12" id="feed">
      <%= render @projects %>
      <%= render no_projects_partial_path(@projects) %>			
    </div>
  </div>	
  
  <div class="infinite-scroll">
    <%= will_paginate @projects %>
  </div>
</div>

app/views/projects/_comment.html.erb
<div class="panel-group">
  <div class="panel panel-info">
    <div class="panel-body">
    <h4><%= comment.author_name %></h4>
      <% if comment.created_at != nil  %>  
       posted <%= distance_of_time_in_words(comment.project.created_at, comment.created_at) %> later
       <br><%= comment.body %></div>
      <% end %>
  </div>
</div>

app/views/projects/_modal.html.erb
<div  class="modal myModal" 
      tabindex="-1" 
      role="dialog" 
      aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <span class="posted-by"></span>
        <button type="button" 
                class="close" 
                data-dismiss="modal" 
                aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-body">
          <div class="loaded-data">
            <h3></h3>
            <p></p>
            <div class="interested"><a href="">See full details</a></div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/projects/_project.html.erb
<%= render project_format_partial_path, project: project %>

app/views/projects/_projects_pagination_page.js.erb
$('#feed').append('<%= j render @projects %>');
<%= render update_pagination_partial_path %>

app/views/projects/javascript.html.erb
<%= render 'projects/modal' %>
<%= render partial: 'projects/branch', locals: { 
    branch: 'javascript',
    page_title: 'Javascript',
    search_placeholder: 'Rock Dodger, Konami Code'
  } %>

app/views/projects/new.html.erb
<div class="container new-project">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Create a new project</h1>
        <%= render 'projects/new/project_form' %>
    </div>
  </div>
</div>

app/views/projects/personal.html.erb
<%= render 'projects/modal' %>
<%= render partial: 'projects/branch', locals: { 
    branch: 'personal',
    page_title: 'Personal',
    search_placeholder: 'Search for personal projects your classmates have made!'
  } %>

app/views/projects/projects.html.erb
<div id="all-project-content" class="container">
  <%@projects.each do |project| %>
  <div class="col-sm-3 single-project-card">
    <div class="card">
      <h4 class="project-text">
        <%= link_to project.title, project_path(project) %>
      </h4>
        <div class="project-text">
          <%= link_to project.description, project%>
        </div>
    </div>
  </div>
  <%end%>
</div>

app/views/projects/rails.html.erb
<%= render 'projects/modal' %>
<%= render partial: 'projects/branch', locals: { 
    branch: 'rails',
    page_title: 'Ruby on Rails',
    search_placeholder: 'Amusement Park, Twitter, FlatCast'
  } %>

app/views/projects/react.html.erb
<%= render 'projects/modal' %>
<%= render partial: 'projects/branch', locals: { 
    branch: 'react',
    page_title: 'React',
    search_placeholder: 'Facebook, Puppy Playhouse, Jersey Shore'
  } %>

app/views/projects/ruby.html.erb
<%= render 'projects/modal' %>
<%= render partial: 'projects/branch', locals: { 
    branch: 'ruby',
    page_title: 'Ruby',
    search_placeholder: 'CLI, Web-Scaper, NOKOGIRI'
  } %>

app/views/projects/show.html.erb
<div id="single-project-content" class="container">
  <div class="row">
  <br>
    <div class="col-sm-6 col-sm-offset-3">
      <div class="panel panel-info panel-body">
        <div class="page-name" >
          <h2><%= @project.title %></h2>
          <h4><%= @flatiron_module.name%></h4>
        </div>
        <div class="posted-by">
          Developed by: <%= @project.user.name %>
        </div>
        <div class="project-text">
          <%= @project.description %>
          <p>
            <a href='<%=@project.github%>' target="_blank">Link to repository</a>
            <br>
            <a href='<%=@project.youtube%>' target="_blank">Link to walkthrough</a>
          </p>
        </div>
        <iframe width="523" height="315" src="<%=@project.youtube%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
        <%if current_user %>
          <div class="page-name">
            <h3>
              <%= link_to 'Post a Comment', new_project_comment_path(@project) %>
            </h3>
            <%= render partial: 'comments/form' %>
          </div>
        <%end%>
      <div class="page-name">
        <h3>
          <%= link_to 'Comments', project_comments_path(@project) %> (<%= @project.comments.size %>)
        </h3>
      </div>
    <%= render partial: 'projects/comment', collection: @project.comments.reverse %>
    </div>
  </div>
</div>

app/views/projects/sinatra.html.erb
<%= render 'projects/modal' %>
<%= render partial: 'projects/branch', locals: { 
    branch: 'sinatra',
    page_title: 'Sinatra',
    search_placeholder: 'E.g. Frank Sinatra, Nancy, Corneal'
  } %>